# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DB_NAME: robotgram
  DB_USERNAME: root
  DB_PASSWORD: secret
  DB_PORT: 27017

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: 'latest'
        mongodb-username: ${{ env.DB_USERNAME }}
        mongodb-password:  ${{ env.DB_PASSWORD }}
        mongodb-db:  ${{ env.DB_NAME }}
        mongodb-port:  ${{ env.DB_PORT }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Go Build
      run: cd backend && go build -v ./...

    - name: Go Tests
      run: cd backend && make test
